### ISSUE TITLE
Bridge returns null pointer for list-mirror entry

### ISSUE THREAD

**Issue by BlackDuck888** [storj/bridge#463] opened 2017-06-07 07:18 UTC
### Package Versions

```
libstor-c-1.0.0-rc7
```

### Expected Behavior

I expect when i query a mirror list, that i only get working/existing entries

### Actual Behavior

If i query mirror-list for bucket: 71571abf30d5e49450a1ee4f  file: d80866e34ae417e015d1575c 

i get this.

```
Established
-----------
Shard: 0
	storj://as50266.net:4000/f6c0e6069c4edadef3047d04fcfae8e1f37eb8e7
	storj://178.63.66.25:54015/f7a4a4b5f7e36d9a33d68fde79d087b02b9d40af
	storj://a.storj.eu:46102/f5bea3f282e1d410b56a8a83f63fd4736b6b9402
	storj://79.143.224.4:4004/f53db06addfc55de4db524283b3b6843aab1824c
	storj://104.168.62.178:4000/f4fd47716ecfdb1eaedf54a4f41fb01f5baf3086

Available
---------
Shard: 0
	storj://158.129.86.2:63776/f6b52bf8ff66f3278964abddfbff54f46401e7b1
	storj://veeit30163.dyndns.org:7007/f5bb2c203a83dac6ec11143c3d195a0e8985f594
	storj://188.79.213.198:36856/f4228f6d4e46b13a888b08b36cca0cfb823313a5
	storj://030s.storjlt.xyz:4100/f7335c93316378800b8bac9786b2b24db70f08fe
	storj://crazyminer.servequake.com:4085/f4eb3f1e6cfef7042ebf918787cba41b7cbf65fd
	storj://storj2.felixbrucker.com:11051/f6e541ed314b438454dae154c606b0a1a70892b4
	storj://188.68.39.133:4000/f64f55bd139a8988c6180d09384be5e401157609
	storj://163.172.80.93:5070/f402360cf35266f93a2aefa9d5735b802f0d9289
	storj://96.42.245.250:31690/f5c0b8fbc5a5b725ab980457e282f79428a7dcf6
	storj://84.238.46.243:48192/f655a9b407869097e099a4ef179220622b878f07
	storj://94.65.89.241:4004/f678121b190a11a65314e7cacdd7a3f556373c53
	storj://(null):(null)/(null)
	storj://47.196.34.90:4000/f7338b5e725b45840f57e5eccf011cd3757b5751
	storj://24.242.238.240:4000/f533acf5547a2693468fbe629881bc4a3586043e
	storj://195.249.163.107:33231/f6c1125bce735c38d9c2a8f1d7fcae13d5656863
	storj://95.211.109.93:4000/f66b6728fa702d99304567568d64584339d0fc8c
	storj://greenspeed.synology.me:4000/f6653b50ad22d4e2ee578a52eaf0b497c3efe140
	storj://95.24.155.48:4000/f69f95c030cf2274dc6c05483d6a4c0f7fa53a60
```

i query these information to generate some stats, my program breaks at these null values.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. query mirror-list for bucket and file above

**Comment by braydonf** [comment] 2017-06-07 12:39
There are some mirrors that are missing associated contact, that's likely the cause.

**Comment by BlackDuck888** [comment] 2017-06-07 14:21
i have a problem with `storj://(null):(null)/(null)` value, why i get null from bridge?

**Comment by RichardLitt** [comment] 2018-10-30 09:37
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!

**Closed by RichardLitt** 2018-10-30 09:37 UTC
Labels: bug
