### ISSUE TITLE
Internal Server error

### ISSUE THREAD

**Issue by littleskunk** [Storj/bridge#316] opened 2016-12-21 09:30 UTC
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
Storjcli: 4.0.0 | Core: 6.0.11
```

Replace the values below using the output from `node --version`.

```
v6.9.2
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
[Wed Dec 21 2016 10:19:13 GMT+0100 (CET)] [debug]  Response Body: "Error: Could not get file, transfer rate limit reached.\n"
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Wed Dec 21 2016 10:25:30 GMT+0100 (CET)] [info]   Resolving 6 file pointers...
 [Wed Dec 21 2016 10:25:31 GMT+0100 (CET)] [debug]  Response Body: "Internal Server Error\n"
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Download a few files to hit the limit
2. Download more files and watch for "Internal Server Error"

**Comment by braydonf** [comment] 2016-12-22 16:41
This is reproducible by trying to login with the incorrect credentials, as the incorrect status code is being used in the responses due to restify defaulting to 500 Internal server error. This has been fixed with https://github.com/Storj/service-error-types/releases/tag/v1.1.0

**Closed by braydonf** 2016-12-22 16:41 UTC
