### ISSUE TITLE
High node response times network wide

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge#508] opened 2017-09-26 18:53 UTC
### Package Versions

Replace the values below using the output from `npm list storj-bridge`.

```
storj-bridge@latest /home/gordon/Code/storj-bridge
└── storj@latest  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
latest
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
Low response times for most nodes.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
The response time of all nodes network wide have been increasing for no apparent reason.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ...
2. ...
3. ...

![response time](https://user-images.githubusercontent.com/11735738/30878212-72ffe3bc-a2fc-11e7-888e-c5b1971dbcbe.png)

**Comment by braydonf** [comment] 2017-09-26 18:54
The timeouts have recently decreased, so may have been after effect of the response time being reset.

**Comment by braydonf** [comment] 2017-09-26 19:35
Duplicate of https://github.com/Storj/complex/issues/76

**Closed by braydonf** 2017-09-26 19:35 UTC
